name: quiz_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  firedart: ^0.9.8
  envied: ^0.5.4+1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  lints: ^5.0.0
  test: ^1.24.0
